name: Deploy to GitHub Pages

on:
  push:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci
        working-directory: Homework-Harvest

      - name: Build static site for web
        run: npx expo export --platform web --public-url https://c22co.github.io/Homework-Harvest-vers2
        working-directory: Homework-Harvest

      - name: Add SPA fallback (404 -> index)
        run: cp dist/index.html dist/404.html
        working-directory: Homework-Harvest

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: Homework-Harvest/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4